### ISSUE TITLE
Database missing

### ISSUE THREAD

**Issue by stevegit23** [miladniroee/php-mvc-simple-framework#1]
Hello - script doesn't create database/table users. If I create a table users with id, name, is_active and populate it, I get an error "foreach() argument must be of type array|object"

**Comment by miladniroee** [comment]
> Hello - script doesn't create database/table users. If I create a table users with id, name, is_active and populate it, I get an error "foreach() argument must be of type array|object"

Yes, because the script for creating tables not implemented at all.

**Comment by stevegit23** [comment]
OK - but how I can fix the error I'm getting with the table I am creating? Id integer AI and primary, name text, is_active (0 or 1)

**Comment by miladniroee** [comment]
> OK - but how I can fix the error I'm getting with the table I am creating? Id integer AI and primary, name text, is_active (0 or 1)

send me your complete error message

**Comment by stevegit23** [comment]
Warning: foreach() argument must be of type array|object, null given in C:\xampp\htdocs\mvctest\Views\index\index.php on line 13

![db1](https://github.com/user-attachments/assets/ef92f538-acaf-4b12-870c-0af5a80c6bb5)
![db2](https://github.com/user-attachments/assets/8a83fcd5-c26b-48dd-bbf6-e6877acb4a85)

**Comment by miladniroee** [comment]
On new version (V2.0) migrations added and this bug has been fixed.
